### ISSUE TITLE
Implement Tests

### ISSUE THREAD

**Issue by jkroepke** [jkroepke/helm-secrets#4]
Run Tests agists different commands:

- [x] helm plugin install #3 
- [x] helm secrets #3 
- [x] helm secrets dec #3 
- [x] helm secrets enc #6 
- [x] helm secrets view #6 
- [x] helm secrets edit #6 
- [x] helm secrets clean #6 
- [x] helm secrets lint #6
- [x] helm secrets template #10 
- [x] helm secrets kubeval #11 
- [x] helm secrets install #12 
- [x] helm secrets upgrade #13
- [x] helm secrets diff #13
